parameters:
  project: ''
  version: ''
  buildConfiguration: ''

steps:
- task: CmdLine@2
  inputs:
    script: |
      for /f "tokens=*" %%i in ('vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe -nologo') do set msbuildpath="%%i"
      
      echo "##vso[task.setvariable variable=msbuildpath]%msbuildpath%"
      %msbuildpath% /t:pack ${{ parameters.project }}/${{ parameters.project }}.csproj /p:NoBuild=true /p:PackageOutputPath="$(Build.ArtifactStagingDirectory)" /p:Authors="Yusuf Tarık Günaydın" /p:Version=${{ parameters.version }} /p:Configuration=${{ parameters.buildConfiguration }}